### ISSUE TITLE
re: screencast keys addon

### ISSUE THREAD

**Issue by meta-androcto** [chromoly/ctools#2]
hello, thank you for your great contributions to blender addons over the years.
A while back ideasman & myself removed screencast keys from blender.
I would add it back for the 2.79 release & would use your version as it's the most recent & the one I recommend all the time.
Thanks for your great contributions & addons, I use your tools all the time.
Thank You.
Brendon
Blender Addons Dev Team

**Comment by chromoly** [comment]
Thank you. I am very happy.
